### PR TITLE
Update to bitflags 2.2.1.

### PR DESCRIPTION
**Pull request by qwandor**

### CODE REVIEW

**Comment by qwandor** [comment]
Hi, would someone be able to take a look at this?

**Comment by lb034582341** [comment]
Hi folks, bumping this up. Is there anything we can do to help push this ? 
The reason why this is important is that the Android Open Source Project uses `anes` amongst other crates. Currently, AOSP both depends on bitflags 1.x.x and bitflags 2.x.x, and we're trying to bring everything to v2.
Thanks!

**Comment by zrzka** [comment]
Sorry folks, I completely missed this one. I'm super busy and I don't have time to maintain this crate. Are any of you willing to take over? I'm willing to transfer this repository to anyone who is going to maintain it (& add you as an owner on crates.io as well).

**Comment by lb034582341** [comment]
That's understandable!
I can't promise a long-term commitment on the crate, or even substantial development time, so I'm unsure if I'm the best fit. However we need this upgrade, so if need be I'm happy to step up and occasionally review incoming PRs.
Except if @qwandor wants to become a maintainer instead

**Comment by qwandor** [comment]
I can take over if need be. Maybe we can both maintain it?

**Comment by zrzka** [comment]
@qwandor AFK now, but I will transfer ownership of this repo to you later today. Can you give me your crates.io username too? Then you'll be able to setup deployments, etc. too.  This is probably the fastest way to unblock y'all. You can also invite others to co-maintain/own the thing too.

**Comment by qwandor** [comment]
Thanks! I'm qwandor there too: https://crates.io/users/qwandor

**Comment by lb034582341** [comment]
Same here: https://crates.io/users/lb034582341
Thanks!

**Comment by zrzka** [comment]
@qwandor GitHub says `qwandor/anes-rs already exists`. Can you drop the fork first? I can't transfer it.

**Comment by qwandor** [comment]
I've renamed it, is that enough?

**Comment by qwandor** [comment]
Deleted it now.

**Comment by zrzka** [comment]
@qwandor transfer requested, invited on crates.io.

**Comment by qwandor** [comment]
Got it, thanks!

**Comment by zrzka** [comment]
Perfect! It's yours, do whatever you think is good to do with it! Enjoy!

P.S. You can remove me as an owner on crates.io, ...

**Pull request closed without merging**
